
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinica?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${password}
    hikari:
      maximum-pool-size: 10         # Numero maximo de conexiones en el pool
      minimum-idle: 5               # Minimo de conexiones inactivas
      idle-timeout: 600000          # Tiempo (ms) antes de cerrar una conexion inactiva
      max-lifetime: 1800000         # Tiempo maximo de vida (ms) de una conexion
      connection-timeout: 30000     # Tiempo de espera para obtener una conexion
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20                 # Agrupa hasta 20 operaciones en lote (inserciones/actualizaciones)
        order_inserts: true              # Ordena las inserciones para optimizar el rendimiento del batch
        order_updates: true              # Ordena las actualizaciones para mejorar el uso del batch


logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: TRACE         # Muestra los valores que se envian a los parametros ?
    org.hibernate.orm.jdbc.extract: TRACE    # Muestra los valores que se extraen desde la BD
    org.hibernate.type.descriptor.sql: TRACE   # Para ver mas detalles de tipos

security:
    jwt:
      secret: TDSZydxbpLTzBiSyAdfK6qzd8nBt9WeOFBO-Pi7NO5X1IWgLA594XmYEj99lEK_ZEyKKs2dkmIe8g1dFBYuQJg
      access-token-expiration: 900000  # 15 minutos en milisegundos
      refresh-token-expiration: 900000  # 15 minutos en milisegundos

server:
  port: 8080
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12